name: 'Build and Test'
on: 
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: 'Install Node'
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    
    - name: 'Install Deps'
      run: npm install
    
    - name: 'Build'
      run: npm run build
    
    - name: 'Test'
      run: npm run coverage
    
    - name: 'Upload coverage reports to Codecov'
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
